export const tools = [
    {
        "id":1,
         "image":"src/images/React-js.png"
    },
    {
        "id":2,
         "image":"src/images/Node-js.png"
    },
    {
        "id":3,
        "image":"src/images/C-sharp.png"
    },
    {
        "id":4,
        "image":"src/images/sql-server.png"
    },
    {
        "id":5,
        "image":"src/images/docker.png"
    },
    {
        "id":6,
        "image":"src/images/mysql.png"
    },
    {
        "id":7,
        "image":"src/images/sequelize.png"
    },
    {
        "id":8,
        "image":"src/images/html-5.png"
    },
    {
        "id":9,
        "image":"src/images/css-3.png"
    },
    {
        "id":10,
        "image":"src/images/js.png"
    },
    {
        "id":11,
        "image":"src/images/mongo.png"
    },
    {
        "id":12,
        "image":"src/images/NET.png"
    },

]